# Generated by Django 3.2.7 on 2021-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HayvanGiris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kupe_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Küpe No')),
                ('pasaport_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Pasaport No')),
                ('padok_no', models.CharField(choices=[(None, 'Padok No Seçiniz'), ('padokno1', 'Padok No1'), ('padokno2', 'Padok No2'), ('padokno3', 'Padok No3')], max_length=50, null=True, verbose_name='Padok No')),
                ('irki', models.CharField(choices=[(None, 'Irk Seçiniz'), ('montofon', 'Montofon'), ('holstein', 'Holstein'), ('simentol', 'Simentol'), ('jersey', 'Jersey'), ('angus', 'Angus')], max_length=50, null=True, verbose_name='IRK')),
                ('alis_fiyati', models.CharField(max_length=50, null=True, verbose_name='Alış Fiyatı')),
                ('satis_fiyati', models.CharField(blank=True, max_length=50, null=True, verbose_name='Satış Fiyatı')),
                ('alis_tarihi', models.DateField(blank=True, null=True, verbose_name='Alış Tarihi')),
                ('cinsiyet', models.CharField(choices=[(None, 'Cinsiyet Seçiniz'), ('bos', 'Belirtmek İstemiyorum'), ('erkek', 'Erkek'), ('duve', 'Düve'), ('inek', 'İnek'), ('malak', 'Malak')], max_length=20, null=True, verbose_name='Cinsiyet')),
                ('isletme', models.CharField(choices=[(None, 'İşletme Seçiniz'), ('isletme1', 'İşletme 1'), ('isletme2', 'İşletme 2'), ('isletme3', 'İşletme 3')], max_length=50, null=True, verbose_name='ISLETME')),
                ('aciklama', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Açıklama')),
                ('alici_bilgi', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Alıcı Bilgi')),
            ],
            options={
                'verbose_name_plural': 'Hayvan',
            },
        ),
    ]
