# Generated by Django 3.2.7 on 2021-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanGirisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hayvangiris',
            name='alis_kg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alış Kg'),
        ),
    ]
