# Generated by Django 3.2.7 on 2021-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hayvanGirisi', '0002_hayvangiris_alis_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hayvangiris',
            name='cinsiyet',
            field=models.CharField(choices=[(None, 'Cinsiyet Seçiniz'), ('erkek', 'Erkek'), ('duve', 'Düve'), ('inek', 'İnek'), ('malak', 'Malak')], max_length=20, null=True, verbose_name='Cinsiyet'),
        ),
    ]
